eco_services_project/src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $designation = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): static
    {
        $this->designation = $designation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }
}

eco_services_project/src/Controller/ServiceCatalogueController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\ServiceRepository;

class ServiceCatalogueController extends AbstractController
{
    #[Route('/service/catalogue', name: 'app_service_catalogue')]
    public function index(ServiceRepository $serviceRepo): Response
    {   
        $service = $serviceRepo->findAll();
        return $this->render('service_catalogue/index.html.twig', [
            'services' => $service,
        ]);
    }
}

eco_services_project/templates/service_catalogue/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue Services{% endblock %}

{% block content %}

<div class="container" id="catalogue_service">
    <div class="breadcrumb">
        <a href="{{ path('home') }}">Accueil</a> <span class="mx-2">/</span> <p class="">Catalogue Services</p>
    </div>
    <div class="row">
        {% for service in services %}
        
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{service.designation}}</h5>
                        <p class="card-text">
                            {{service.description}}
                        </p>
                        <a href="{{ path('add_to_request', { 'service_id': service.id, 'quantity':50 }) }}" class="btn border m-bg-primary text-white">Sélectionner ce service</a>
                    </div>
                </div>
            </div>
        
        {% endfor %}
    </div>
</div>
{% endblock %}